/* Do not edit - Machine generated */
#ifndef _INC_REACTOS_BUILDNO
#define _INC_REACTOS_BUILDNO
#define KERNEL_VERSION_BUILD	6238
#define KERNEL_VERSION_BUILD_STR	"6238"
#define KERNEL_RELEASE_RC	"0.0.17.6238\0"
#define KERNEL_RELEASE_STR	"0.0.17.6238"
#define KERNEL_VERSION_RC	"0.0.17\0"
#define KERNEL_VERSION_STR	"0.0.17"
#endif
/* EOF */
